version: '3.8'

services:
  php-server-manager:
    build: .
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/root/.php-server-manager
    privileged: true
    network_mode: host
    environment:
      - PHP_SERVER_PASSWORD=your_secure_password_here
    restart: unless-stopped
